// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE44bcf2dDecodeGithubComLutomasSwagger2MdTypes(in *jlexer.Lexer, out *ObjectType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "format":
			if in.IsNull() {
				in.Skip()
				out.Format = nil
			} else {
				if out.Format == nil {
					out.Format = new(string)
				}
				*out.Format = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				*out.Description = string(in.String())
			}
		case "required":
			if in.IsNull() {
				in.Skip()
				out.Required = nil
			} else {
				in.Delim('[')
				if out.Required == nil {
					if !in.IsDelim(']') {
						out.Required = make([]string, 0, 4)
					} else {
						out.Required = []string{}
					}
				} else {
					out.Required = (out.Required)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Required = append(out.Required, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "$ref":
			if in.IsNull() {
				in.Skip()
				out.Ref = nil
			} else {
				if out.Ref == nil {
					out.Ref = new(string)
				}
				*out.Ref = string(in.String())
			}
		case "enum":
			if in.IsNull() {
				in.Skip()
				out.Enum = nil
			} else {
				in.Delim('[')
				if out.Enum == nil {
					if !in.IsDelim(']') {
						out.Enum = make([]string, 0, 4)
					} else {
						out.Enum = []string{}
					}
				} else {
					out.Enum = (out.Enum)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					v2 = string(in.String())
					out.Enum = append(out.Enum, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "properties":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Properties = make(map[string]*ObjectType)
				} else {
					out.Properties = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 *ObjectType
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(ObjectType)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v3).UnmarshalJSON(data))
						}
					}
					(out.Properties)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		case "example":
			if m, ok := out.Example.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Example.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Example = in.Interface()
			}
		case "allOf":
			if in.IsNull() {
				in.Skip()
				out.AllOf = nil
			} else {
				in.Delim('[')
				if out.AllOf == nil {
					if !in.IsDelim(']') {
						out.AllOf = make([]*ObjectType, 0, 8)
					} else {
						out.AllOf = []*ObjectType{}
					}
				} else {
					out.AllOf = (out.AllOf)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *ObjectType
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(ObjectType)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v4).UnmarshalJSON(data))
						}
					}
					out.AllOf = append(out.AllOf, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				if out.Items == nil {
					out.Items = new(ObjectType)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Items).UnmarshalJSON(data))
				}
			}
		case "additionalProperties":
			if in.IsNull() {
				in.Skip()
				out.AdditionalProperties = nil
			} else {
				if out.AdditionalProperties == nil {
					out.AdditionalProperties = new(ObjectType)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.AdditionalProperties).UnmarshalJSON(data))
				}
			}
		case "maxLength":
			if in.IsNull() {
				in.Skip()
				out.MaxLength = nil
			} else {
				if out.MaxLength == nil {
					out.MaxLength = new(int64)
				}
				*out.MaxLength = int64(in.Int64())
			}
		case "minLength":
			if in.IsNull() {
				in.Skip()
				out.MinLength = nil
			} else {
				if out.MinLength == nil {
					out.MinLength = new(int64)
				}
				*out.MinLength = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE44bcf2dEncodeGithubComLutomasSwagger2MdTypes(out *jwriter.Writer, in ObjectType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.Format != nil {
		const prefix string = ",\"format\":"
		out.RawString(prefix)
		out.String(string(*in.Format))
	}
	if in.Description != nil {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(*in.Description))
	}
	if len(in.Required) != 0 {
		const prefix string = ",\"required\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Required {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	if in.Ref != nil {
		const prefix string = ",\"$ref\":"
		out.RawString(prefix)
		out.String(string(*in.Ref))
	}
	if len(in.Enum) != 0 {
		const prefix string = ",\"enum\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v7, v8 := range in.Enum {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	if len(in.Properties) != 0 {
		const prefix string = ",\"properties\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.Properties {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				if v9Value == nil {
					out.RawString("null")
				} else {
					out.Raw((*v9Value).MarshalJSON())
				}
			}
			out.RawByte('}')
		}
	}
	if in.Example != nil {
		const prefix string = ",\"example\":"
		out.RawString(prefix)
		if m, ok := in.Example.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Example.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Example))
		}
	}
	if len(in.AllOf) != 0 {
		const prefix string = ",\"allOf\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v10, v11 := range in.AllOf {
				if v10 > 0 {
					out.RawByte(',')
				}
				if v11 == nil {
					out.RawString("null")
				} else {
					out.Raw((*v11).MarshalJSON())
				}
			}
			out.RawByte(']')
		}
	}
	if in.Items != nil {
		const prefix string = ",\"items\":"
		out.RawString(prefix)
		out.Raw((*in.Items).MarshalJSON())
	}
	if in.AdditionalProperties != nil {
		const prefix string = ",\"additionalProperties\":"
		out.RawString(prefix)
		out.Raw((*in.AdditionalProperties).MarshalJSON())
	}
	if in.MaxLength != nil {
		const prefix string = ",\"maxLength\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MaxLength))
	}
	if in.MinLength != nil {
		const prefix string = ",\"minLength\":"
		out.RawString(prefix)
		out.Int64(int64(*in.MinLength))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ObjectType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE44bcf2dEncodeGithubComLutomasSwagger2MdTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ObjectType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE44bcf2dEncodeGithubComLutomasSwagger2MdTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ObjectType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE44bcf2dDecodeGithubComLutomasSwagger2MdTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ObjectType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE44bcf2dDecodeGithubComLutomasSwagger2MdTypes(l, v)
}
